[package]
name = "chance-staking-common"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
